### ISSUE TITLE
EnforceMeltingTemperature crashes with default location

### ISSUE THREAD

**Issue by Thopic** [Edinburgh-Genome-Foundry/DnaChisel#89]
Hi, thanks a lot for the great package!

Small issue, but we were trying to use `EnforceMeltingTemperature` to generate some primers and it fails if you don't put the `location` argument (location=None crashes). 

```py
from dnachisel import DnaOptimizationProblem, random_dna_sequence
from dnachisel.builtin_specifications import (
    EnforceMeltingTemperature,
)


def create_new_primer():
    """Create a new primer. """
    problem = DnaOptimizationProblem(
        sequence=random_dna_sequence(length=20),
        objectives=[EnforceMeltingTemperature(mini=20, maxi=86, boost=1.0)]
    )
    problem.resolve_constraints()
    problem.optimize()
    return problem.sequence

create_new_primer()
```
Will return:
```
AttributeError: 'NoneType' object has no attribute 'extract_sequence'
```

Best,
Thomas

**Comment by veghp** [comment]
Thank you very much for bringing attention to this!

The issue was a typo in `EnforceMeltingTemperature.initialized_on_problem()`.

The error message didn't point to it, because `EnforceMeltingTemperature` inherited a method with the same name from `Specification`.

I'll add a test to call EnforceMeltingTemperature, then release it.
